from app.topic.interpreter.base import BaseTopicInterpreter


class RuleBasedInterpreter(BaseTopicInterpreter):

    CATEGORY_RULES = {

        "Teknologi": [
            "ai",
            "openai",
            "chatgpt",
            "google",
            "microsoft",
            "apple",
            "android",
            "iphone",
            "chip",
            "samsung",
            "internet",
            "komputer",
            "startup",
            "deepseek",
            "gpu",
            "nvidia",
            "teknologi",
            "digital",
            "aplikasi",
            "software",
            "hardware",
            "server",
            "cloud",
            "cyber",
            "keamanan",
            "siber",
            "data",
            "robot",
            "robotik",
            "iot",
            "artificial",
            "machine",
            "learning",
            "website",
            "platform",
            "meta",
            "tesla",
            "intel",
            "amd",
        ],

        "Ekonomi": [
            "ihsg",
            "bank",
            "rupiah",
            "investasi",
            "inflasi",
            "ekonomi",
            "saham",
            "bisnis",
            "pajak",
            "bumn",
            "koperasi",
            "usaha",
            "umkm",
            "proyek",
            "groundbreaking",
            "masela",
            "migas",
            "energi",
            "pertamina",
            "bbm",
            "listrik",
            "pln",
            "ekspor",
            "impor",
            "perdagangan",
            "keuangan",
            "industri",
            "manufaktur",
            "harga",
            "pasar",
            "dolar",
            "bea",
            "cukai",
        ],

        "Politik": [
            "presiden",
            "prabowo",
            "dpr",
            "menteri",
            "pemilu",
            "politik",
            "istana",
            "kpu",
            "wapres",
            "gubernur",
            "bupati",
            "wali",
            "kepala",
            "daerah",
            "kabinet",
            "kementerian",
            "asn",
            "pegawai",
            "jaksa",
            "kejaksaan",
            "jagung",
            "kpk",
            "korupsi",
            "mk",
            "mahkamah",
            "parlemen",
            "partai",
            "fraksi",
            "legislatif",
            "eksekutif",
        ],

        "Olahraga": [
            "bola",
            "timnas",
            "liga",
            "piala",
            "fifa",
            "afc",
            "persib",
            "persija",
            "gol",
            "pelatih",
            "pertandingan",
            "sepak bola",
            "olahraga",
            "atlet",
            "badminton",
            "voli",
            "basket",
            "piala",
            "dunia",
            "pildun",
            "gol",
            "laga",
            "pertandingan",
            "juara",
            "pelatih",
            "pemain",
            "sepak",
            "olahraga",
            "afc",
            "uefa",
            "basket",
            "voli",
            "tenis",
            "atlet",
            "olimpiade",
            "kejuaraan",
        ],

        "Internasional": [
            "amerika",
            "china",
            "jepang",
            "israel",
            "iran",
            "rusia",
            "ukraina",
            "eropa",
            "asia",
            "global",
            "internasional",
            "tiongkok",
            "korea",
            "inggris",
            "prancis",
            "jerman",
            "india",
            "pakistan",
            "gaza",
            "hamas",
            "timur",
            "tengah",
            "nato",
            "pbb",
            "unesco",
            "asean",
            "amerika serikat",
        ],

        "Kesehatan": [
            "covid",
            "rumah",
            "sakit",
            "vaksin",
            "dokter",
            "pasien",
            "virus",
            "kesehatan",
            "bpjs",
            "obat",
            "medis",
            "klinik",
            "perawat",
            "gizi",
            "stunting",
            "demam",
            "diare",
            "dbd",
            "flu",
            "kanker",
            "jantung",
            "hipertensi",
        ],
            "Pendidikan": [
            "sekolah",
            "guru",
            "murid",
            "siswa",
            "mahasiswa",
            "kampus",
            "universitas",
            "kuliah",
            "pendidikan",
            "ajar",
            "didik",
            "beasiswa",
            "kurikulum",
            "rektor",
        ],

        "Hukum": [
            "hakim",
            "sidang",
            "pengadilan",
            "putusan",
            "vonis",
            "tersangka",
            "terdakwa",
            "pidana",
            "perdata",
            "hukum",
            "kejaksaan",
            "jaksa",
        ],

    }

    def interpret(self, keywords):

        scores = {}

        for category, words in self.CATEGORY_RULES.items():

            score = 0

            for keyword in keywords:

                if keyword.lower() in words:

                    score += 1

            scores[category] = score

        category = max(
            scores,
            key=scores.get,
        )

        if scores[category] == 0:

            return "Lainnya"

        return category